### ISSUE TITLE
Dad Jokes Recycler View from Firebase DB

### ISSUE THREAD

**Issue by Sabihashaik** [theDroidCamp/DadJokes_intermediate#15]
- Create a Firebase DB with some sample dad jokes
- Pull the data from this database and display in a recycler view or list view

**Comment by DaChelimo** [comment]
Could you assign this to me?

**Comment by nasreekar** [comment]
@Sabihashaik  are we creating our own db for dad jokes or are we displaying them from an API?

**Comment by DaChelimo** [comment]
Currently, I'm fetching them from an API. I'll push tomorrow.

**Comment by DaChelimo** [comment]
@nasreekar Or what did you have in mind?

**Comment by DaChelimo** [comment]
Already merged a PR solving this issue
